data<- read.table("household_power_consumption.txt", na.strings = "?", header = TRUE, sep =";" )
DateTime<- strptime(paste(data$Date, data$Time, sep= " "), "%d/%m/%Y %H:%M:%S")
data<- cbind(data, DateTime)
data$Date<- as.Date(data$Date, format="%d/%m/%Y")
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)
data2<- subset(data, Date=="2007-02-01"|Date=="2007-02-02")
png("plot3.png", width = 480, height = 480)
with(data2, plot(DateTime, Sub_metering_1, type="l", ylab= "Energy sub metering", xlab=" "))
lines(data2$DateTime, data2$Sub_metering_2, type="l", col="red")
lines(data2$DateTime, data2$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=1, col=c("black", "red", "blue"))
dev.off()
